export type InventoryItem = {
  inventoryId: number;
  itemId: number;
  itemCode?: string;
  itemName: string;
  categoryId?: number;
  categoryName: string;
  uomName: string;
  locationId: number;
  locationName: string;
  currentStock: number;
  reservedStock?: number;
  availableStock?: number;
  minStockLevel: number;
  maxStockLevel: number;
  isLowStock: boolean;
  isOverStock?: boolean;
  isActive?: boolean;
  isLotTracked?: boolean;
  isExpiryTracked?: boolean;
};
