name: Build Next.js App

on:
  workflow_call:
    inputs:
      name:
        description: 'Name of the workflow'
        required: true
        type: string
      port:
        description: 'Container port exposed by the app'
        required: false
        default: '3004'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules and Next.js cache
        uses: actions/cache@v4
        with:
            path: |
                ~/.npm
                ${{ github.workspace }}/.next/cache
            key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
            restore-keys: |
                ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Build Next.js app
        run: npm run build
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: http://localhost:${{ inputs.port }}
          NEXT_PUBLIC_API_URL: http://localhost:5006/
          NEXT_PUBLIC_HOST_URL: http://localhost:3000
          NEXT_PUBLIC_HRMS_URL: http://localhost:3001
          NEXT_PUBLIC_POS_URL: http://localhost:3002
          NEXT_PUBLIC_SCMS_URL: http://localhost:3003
          NEXT_PUBLIC_OOS_URL: http://localhost:3004
          NEXT_PUBLIC_CRMS_URL: http://localhost:3005
          NODE_TLS_REJECT_UNAUTHORIZED: 0



      - name: Run tests
        run: npm test --if-present
